 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Jul/2023 14:14:52] "[37mGET / HTTP/1.1[0m" 200 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:9000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Jul/2023 14:33:10] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [07/Jul/2023 14:33:20] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [07/Jul/2023 14:34:05] "[33mPOST /login/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:35:34] "[33mPOST /login/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:35:47] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [07/Jul/2023 14:35:47] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [07/Jul/2023 14:35:57] "[33mPOST /login/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:36:05] "[33mPOST /login/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:37:00] "[33mPOST /login/v1 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:42:33] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:42:49] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "password-evolution.py", line 85, in <module>
    app.run(host='0.0.0.0', port=9000, ssl_context='adhoc')
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [07/Jul/2023 14:43:10] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:45:02] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [07/Jul/2023 14:45:26] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "password-evolution.py", line 91, in <module>
    app.run(host='0.0.0.0', port=9000, ssl_context='adhoc')
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/devasc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [07/Jul/2023 14:51:12] "[33mPOST /signup/v2 HTTP/1.1[0m" 404 -
